### ISSUE TITLE
Todo Example Application

### ISSUE THREAD

**Issue by jxson** [vanadium/baku#1]
Punch List
- [ ] Look into using a builder for creating row items (`LazyBlock`).
- [ ] Use callbacks for handling dialog actions instead of the return future from `showDialog`.
- [ ] Clean up the dialog form & inputs.
- [ ] DRY up repetitive code.
- [ ] Add Task and List editing.
- [ ] Add undo functionality.
- [ ] Clean up rows: correct meta, relative time, etc.
- [ ] Task completion needs to be set up better. Perhaps a sorted data structure would be better for having completed tasks move down the list.
- [ ] Use `UUID` type instead of String where ids are arguments.
- [ ] Show empty/filled checkboxes in the Tasks View. This is a new click target.
- [ ] Move Mark All Tasks as Done from the LoL View to the overflow menu of the Tasks View
- [ ] Put Edit List and Delete List actions into overflow of Tasks View
- [ ] Do some background color tweaking for "Done" items. They should be harder to see, opacity-wise as well.
- [ ] Blank slate screen
- [ ] Discovery slider
- [ ] Not found route (see @aghassemi's comment [here](https://vanadium-review.googlesource.com/#/c/22598/1/examples/todos/lib/main.dart@51), also [related](https://github.com/flutter/flutter/issues/4087)).
- [ ] Stub store and firebase.
- [ ] Visual cleanup.
- [ ] Sharing.
